name: my_coins
description: Simples consulta a cotação de moedas

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+15

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  dio: ^4.0.0
  fpdart: ^0.0.10
  intl: ^0.17.0
  package_info: ^2.0.2
  #url_launcher: ^6.1.4
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.9.1
  rate_my_app: ^1.1.0+1
  launch_review: ^3.0.1
  firebase_analytics: ^8.3.4
  firebase_core: ^1.8.0
  chart_sparkline: ^1.0.5
  screenshot: ^1.2.3
  share_plus: ^4.0.7
  path_provider: ^2.0.6
  onesignal_flutter: ^3.2.7
  numberpicker: ^2.1.1
  

flutter_icons:
  image_path_ios: "images/logo.png"
  image_path_android: "images/logo.png"
  android: true
  ios: true

dev_dependencies:
  modular_test: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  mocktail: ^0.1.4
  cider: 

flutter:
  uses-material-design: true

  fonts:
  - family: RobotoSlab
    fonts:
      - asset: fonts/RobotoSlab-Regular.ttf
  - family: RobotoSlabBold
    fonts:
      - asset: fonts/RobotoSlab-Bold.ttf   
  - family: RobotoSlabLight
    fonts:
      - asset: fonts/RobotoSlab-Light.ttf  