name: my_coins
description: Simples consulta a cotação de moedas

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5 
  dio: ^5.1.1   
  fpdart: ^1.1.1
  intl: ^0.20.2 
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.14.3
  rate_my_app: ^2.3.1
  launch_review_latest: ^1.0.0
  #firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  chart_sparkline: ^1.0.5
  screenshot: ^3.0.0
  share_plus: ^7.2.1
  path_provider: ^2.0.15
  onesignal_flutter: ^5.0.4
  numberpicker: ^2.1.1
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.4

flutter_icons:
  image_path_ios: "images/logo.png"
  image_path_android: "images/logo.png"
  android: true
  ios: true

dev_dependencies:
  modular_test: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.3.3
  mocktail: ^1.0.4
  cider: ^0.2.7

flutter:
  uses-material-design: true

  fonts:
  - family: RobotoSlab
    fonts:
      - asset: fonts/RobotoSlab-Regular.ttf
  - family: RobotoSlabBold
    fonts:
      - asset: fonts/RobotoSlab-Bold.ttf   
  - family: RobotoSlabLight
    fonts:
      - asset: fonts/RobotoSlab-Light.ttf  