default_platform(:android)

platform :android do
  desc "Suite de tests "
  lane :tests do
    gradle(task: "test")
  end
  desc "Deploy nova versão para Google Play Store"
  lane :publish do
    begin      
      initialDir = Dir.pwd 

      #newVersion = ""

      Dir.chdir("../..") do
        sh("cider bump build")
        sh("cider bump minor --keep-build")
        puts Dir.pwd
      end

      Dir.chdir(initialDir) do
        #newVersion = "#{flutter_version()['version_name']}+#{flutter_version()['version_code']}"

        sh("flutter clean")
        sh("flutter pub get")
        sh("flutter build appbundle --release")

        upload_to_play_store(
          aab: "../build/app/outputs/bundle/release/app-release.aab",
          track: "production",
          skip_upload_images: true,
          skip_upload_screenshots: true,
          skip_upload_apk: true,
          validate_only: false
        )

        Dir.chdir("../..") do
          sh("git add pubspec.yaml")
          sh("git commit -m 'fastlane publish'")
          sh("git tag -a  'v1.1.0+12' -m 'Release'")
          sh("git push origin")
        end
        
      rescue => exception
        Dir.chdir("../..") do
          sh("git checkout pubspec.yaml")
        end

        raise exception unless exception.message.include?('APK specifies a version code that has already been used.')
        puts 'Essa versão de código já está em uso 🤨'
      end

    end

  end

end
